// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb47Im0md5CweqSsSvXbnAFR38nqTnQBo',
    appId: '1:661854976985:web:80429e5dd007b2f8f1f7c8',
    messagingSenderId: '661854976985',
    projectId: 'chat-app-492fe',
    authDomain: 'chat-app-492fe.firebaseapp.com',
    storageBucket: 'chat-app-492fe.appspot.com',
    measurementId: 'G-0GVYY02LD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdbG0qqwjg60h4PUMjjtEaAH50HiD3m4',
    appId: '1:661854976985:android:470ea1e6475d72bef1f7c8',
    messagingSenderId: '661854976985',
    projectId: 'chat-app-492fe',
    storageBucket: 'chat-app-492fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3OW4qGzhZNZAEBoqY9C7TRJoMDswVXlw',
    appId: '1:661854976985:ios:3f9835c9c38a3656f1f7c8',
    messagingSenderId: '661854976985',
    projectId: 'chat-app-492fe',
    storageBucket: 'chat-app-492fe.appspot.com',
    iosClientId: '661854976985-b8ckbcijivbg3sq13qi2d938s20n7fjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3OW4qGzhZNZAEBoqY9C7TRJoMDswVXlw',
    appId: '1:661854976985:ios:36add284679c44f4f1f7c8',
    messagingSenderId: '661854976985',
    projectId: 'chat-app-492fe',
    storageBucket: 'chat-app-492fe.appspot.com',
    iosClientId: '661854976985-sbqpiu0hsivav4ccs2t1jgjpibc07uv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
